name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/linux-to-telegram-backup:latest  --tag ${{ secrets.DOCKERHUB_USER }}/linux-to-telegram-backup:${{ vars.VERSION }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/linux-to-telegram-backup:${{ vars.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USER }}/linux-to-telegram-backup:latest